blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/ACS-UI/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for ProGenTeam
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=ProGenTeam.roo-cline&ssr=false#review-details
      about: Enjoying ProGenTeam? Leave a review here!
